### ISSUE TITLE
"include_trashed" doesn't work for models that inherit the SoftDeletes trait

### ISSUE THREAD

**Issue by ramirezd42** [cviebrock/eloquent-sluggable#136]
I have a model that extends from a base class that uses the **SoftDeletes** trait and I'm unable to use the **include_trashed** configuration option. 

This is because **SluggableTrait** utilizes PHP's built in **class_uses()** function to search through a list of the model's traits, which does not include traits included by parent classes. See below:
```php
	protected function usesSoftDeleting() {
		return in_array('Illuminate\Database\Eloquent\SoftDeletes', class_uses($this));
	}
```

The result is that trashed models are not included when getting the list of existing slugs. I propose expanding upon the **usesSoftDeleting** function to retrieve traits for parent classes as well.

**Comment by cviebrock** [comment]
Ah ... damn.  Thanks for catching this.  Yeah, it'll need to be fixed.

Are you able to make an PR to fix this, or at least a PR for a test that shows it's broken?

**Comment by ramirezd42** [comment]
Yeah sure.

Here's a pull request that resolves this issue by looping through parent classes as well and checking the traits of each: https://github.com/cviebrock/eloquent-sluggable/pull/139

**Comment by cviebrock** [comment]
I just thought about this some more ... might it be easier to just check if the current class (i.e. the model) has a `public static function bootSoftDeletes()` method?

Otherwise, what if your parent class extends another parent that includes the Sluggable trait? Or, there is a trait that extends the Sluggable trait? Rather than do through all these recursive tests, just check for the existence of a method or property that signifies that soft deleting is enabled.

What do you think?

**Comment by ramirezd42** [comment]
That seems like a simpler solution. I updated the pull request to do it that way (https://github.com/cviebrock/eloquent-sluggable/pull/139)

**Comment by cviebrock** [comment]
Thanks ... let me know how it goes!
