### ISSUE TITLE
Slug including the primary key causes problems

### ISSUE THREAD

**Issue by barryvanveen** [cviebrock/eloquent-sluggable#137]
I've been using the SluggableTrait for some time now and it really helped me a lot, thanks for the good work! Yesterday, after some changes I ran into a small problem when using the primary key in the slug.

For my blogposts I want to use slugs of the form [id]-[title-as-a-slug]. This way I can change my title and update the slug and still redirect people to the correct page. So, if my slug is like "1-my-first-blog" it can be updated to "1-updated-my-first-blog" without any problems because I identify the blogpost by its id and not by the entire slug. I thought that creates a nice descriptive url.

There is just one little problem. The initial slug is not created properly because when the `eloquent.saving*` event is fired a new blogpost doesn't have any id, that is only created when the database record is created. So instead of "1-my-first-blog" I get "my-first-blog" and only after updating the blogpost the slug is set at "1-my-first-blogpost".

Is there any particular reason why eloquent-sluggable uses the `eloquent-saving*` event and not the `eloquent-saved*` event? Changing the event would allow anybody to use id's in their slugs without any problems.

**Comment by cviebrock** [comment]
Thanks for the compliments!

As for why I use the `saving` event and not `saved` ... with `saving`, you can a) check if certain fields have changed and only regenerate the slug if required which b) prevents multiple hits to the database.  Once you are in the `saved` event, you don't have access to the previous attribute values, and you can't do some of the checks that are currently required.

(I'm not suggesting that there isn't a way to refactor the package to use `saved` instead of `saving`. But it would probably necessitate many other adjustments to how things are currently done, breaking some backwards compatibility along the way, especially with the `on_updated` config setting.)

There was a previous issue about someone who wanted to use the model ID in the slug, and my suggestion at the time was that was slightly the wrong way of solving the problem.  What I'm guessing you really want is to include the model ID in a _URL_ you can route to.  In this case, I'd suggest just changing your route to be something like:

```php
Route::get('articles/{id}-{slug}', function($id, $slug) {
    // do stuff (maybe starting with confirming that the slug and id match the same model)
});
```

Maybe even through in some pattern filtering before hand:

```php
Route::pattern('id', '[0-9]+');
Route::pattern('slug', '[a-z0-9\-]+');
```

Would that solve your particular use-case?

**Comment by barryvanveen** [comment]
Thanks for the suggestion, I don't know why I never thought of that before. It works perfectly and it makes for a much more elegant solution!
