### ISSUE TITLE
Potential Issue with Oberserver

### ISSUE THREAD

**Issue by areindl** [cviebrock/eloquent-sluggable#140]
Hi.

I have a Model called "Project" and a model called "Phase". Whenever a new Project ist created, a set of predefined Phases will be initialized. I implemented this by issuing an Oberserver.

The Oberserver listens for the "created" event that is fired by the Project model. I noticed that since then, the automatic sluggify mechanism seemed to stopped word. 

I solved the issue by adding $model->sluggify() to my created method in the Observer.

Did someone notice the same behaviour?

Best,
Anton

**Comment by cviebrock** [comment]
You are saying the slugging of your Project model stopped working once you implemented an observer? This could be because of how I listen for the _saving_ event in the service provider, and it might conflict with model observers.

Although, that seems weird because they are two different events (_saving_ and _created_).

If you can make a PR with a test that shows the failing behaviour, I can take a look.

**Comment by cviebrock** [comment]
Closed for lack of response. :(
