### ISSUE TITLE
Russian Issue

### ISSUE THREAD

**Issue by jenistar90** [cviebrock/eloquent-sluggable#175]
I am going to make the slug, but the origin word is Russian.
In that case, it occurs the error. Any Idea?

**Comment by cviebrock** [comment]
What error? And what version of sluggable?

**Comment by jenistar90** [comment]
I don't know it's version correctly.
It is 2.x version.

And here is the screenshot of the error.

**Comment by cviebrock** [comment]
Hrm. I don't use the `iconv()` function in the package, and I don't think Laravel does in `Str::slug()`, which was the default slugging method for the 2.x branch.

A bit of googling turns up this: <https://github.com/tedious/Fetch/issues/13>  Maybe it's an issue with PHP 5.3, if you are running that? Or some other encoding that you're doing?

Can you not upgrade the package to the 3.0 version and see if that helps?

**Comment by jenistar90** [comment]
Thanks for your replying.

I read this article, and this was super help for me.

http://habrahabr.ru/post/208678/

**Comment by cviebrock** [comment]
I read through that article (or at least the Google Translate version).  Yes, I think your issue was simply that `Str::slug()` -- the default slugging engine for the 2.x branch -- can't handle Cyrillic characters.

The 3.x releases use <https://github.com/cocur/slugify>, which has special rules for non-ASCII characters.

If you need to stick with the 2.x branch, you can emulate this by following the instructions mentioned in issue #98.

**Comment by jenistar90** [comment]
Thanks million. (y)
