### ISSUE TITLE
Route-model Binding in L5.2

### ISSUE THREAD

**Issue by royduin** [cviebrock/eloquent-sluggable#223]
It looks like this is not working with L5.2:
```
$app->singleton(
    'router',
    '\Cviebrock\EloquentSluggable\SluggableRouter'
);
```

Some already present interfaces looks like:
```
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);
```

I've tried to "convert" it to work with 5.2 but with or without it's not producing any errors but `Auth::user()->sites()->findBySlug($slug);` is still not working in my controller (which does produce errors `Call to undefined method`). For the time being I'm using `Auth::user()->sites()->whereSlug($slug)->first();` but it's not that clean.

Any ideas how to get this working with Laravel 5.2?

A part of my controller:
```
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Site;
use Auth;

class SiteController extends Controller
{
	public function show($slug)
	{
		$site = Auth::user()->sites()->whereSlug($slug)->first();
		return view('site.show', compact('site'));
	}
}
```

And a part of my model:
```
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Site extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'name',
        'save_to'    => 'slug',
        'max_length' => 250,
        'on_update'  => true
    ];

    protected $fillable = [
        'name', 'info'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}
```

**Comment by spitzgoby** [comment]
I had a similar issue. Currently my solution is to manually bind the static `findBySlugOrIdOrFail` within `app/Providers/RouteServiceProvider.php`.

    /* in RouteServiceProvider.php */
    public function boot(Router $router)
    {
        $router->bind('site', function($value) {
            return Site::findBySlugOrIdOrFail($value);
        });

        parent::boot($router);
    }

Make sure that the keyword you're binding (`'site'` in this case) exactly matches the route parameter in your `routes.php` file. If you're not sure which to use you can use the `php artisan route:list` command to get a complete list of routes and their parameters.  

Finally, change your `SiteController@show` method so that it type hints the object it expects to receive.
    
    /* in SiteController.php */
    public function show(Site $site)
    {
        return view('site.show', compact('site'));
    }

Now your `$site` object will be created automatically for you. If the slug or id could not be found a `ModelNotFoundException` will be thrown instead.

**Comment by royduin** [comment]
Thanks @spitzgoby, meanwhile I've fixed it by setting the `getRouteKeyName()` function on my models:
```
public function getRouteKeyName()
{
    return 'slug';
}
```
Pretty simple and it works perfectly!
