### ISSUE TITLE
Fix installation part

### ISSUE THREAD

**Issue by Shandur** [cviebrock/eloquent-sluggable#295]
Hi!
You haven't pointed put in your installation guide that class using the slugger must implement SluggableInterface. 
I waisted some time to understand why it's not working.
Please, add it 'cause it's really important.
Hope it saves someones time!
[Picture](http://joxi.ru/L21XqbYtvNMgmX)

**Comment by cviebrock** [comment]
You must be using an old version of that package, because that's not required anymore.

The [usage instructions](https://github.com/cviebrock/eloquent-sluggable#updating-your-eloquent-models) on GitHub show what you need.  If you are using a different version, then check the README that came with your pacakge (or change to the appropriate branch/tag on Github).
