### ISSUE TITLE
`onUpdate` bug

### ISSUE THREAD

**Issue by RomaGilyov** [cviebrock/eloquent-sluggable#317]
Have an issue with `onUpdate` option, I made it true and after that each time a model was updated slug increments in any case, even if I don't update `source` fields. How can I fix this?

**Comment by Barcelonczyk** [comment]
I have the same problem and made little investigation. 
The bug occurs only when another item has the same slug source like the one we're updating. In this case we should return previously generated slug.

Changing makeSlugUnique method in SlugService should solve this problem (I made small tests and it looks ok). 

Change:
<pre><code>
if (
	$list->count() === 0 ||
	$list->contains($slug) === false ||
	(
		$list->has($this->model->getKey()) &&
		$list->get($this->model->getKey()) === $slug
	)
) {
	return $slug;
}
</code></pre>

To:
<pre><code>
if (
	$list->count() === 0 ||
	$list->contains($slug) === false ||
	(
		$list->has($this->model->getKey()) &&
		$list->get($this->model->getKey()) === $slug
	)
) {
	return $slug;
} elseif ($list->has($this->model->getKey())) {
	$pattern = '/^' . $slug . $separator . '[0-9]+$/';
	$subject = $list->get($this->model->getKey());
	if (preg_match($pattern, $subject)) {
		return $subject;
	}
}
</code></pre>
Instead of regex it should be better to just check currently assigned slug, but i don't know how to get it without lots of additional code.

**Comment by cviebrock** [comment]
Do you mind trying the master branch? I changed the code a bit in the SlugService to look for "similar" slugs, in addition to an exact match ... pretty much what you did above, but without regex. :)

My tests pass, but let me know if it works in your case.  If so, I'll push a new release.

**Comment by Barcelonczyk** [comment]
I tried master branch, it works fine for me. Thanks for fix 👍

**Comment by RomaGilyov** [comment]
Works well for me as well :+1: Thanks a lot!

**Comment by cviebrock** [comment]
Cool, thanks folks! I'll push 4.1.1 shortly.
