### ISSUE TITLE
Default RouteKeyName

### ISSUE THREAD

**Issue by socieboy** [cviebrock/eloquent-sluggable#352]
You should add on the sluggable trait "slug" as defaultRouteKeyName.

```
    public function getRouteKeyName()
    {
        return 'slug';
    }
```

**Comment by cviebrock** [comment]
See https://github.com/cviebrock/eloquent-sluggable/blob/master/ROUTE-MODEL-BINDING.md

**Comment by socieboy** [comment]
I know is easy to implement, but if we are using this package for slug, basically we need to find a model by slug, would be nice if the sluggable trait has this method already implemented, so i don't need to implement in all my models where i use the sluggable trait.

**Comment by cviebrock** [comment]
The flip side of that, is that people may want to use the package/trait and _not_ have this setting changed (because they are not using Route-Model binding, or are using a different key name other than `slug`).

Why not just make your own trait that just adds that function and use it in your own models:

```php
trait SetsSlugRouteKeyName {
    public function getRouteKeyName()
    {
        return 'slug';
    }
}
```

And then: 

```php
class MyModel extends Eloquent {
    use Sluggable;
    use SetsSlugRouteKeyName;

    ...
}
```
