### ISSUE TITLE
Slug isn't created if `name` is null

### ISSUE THREAD

**Issue by GoodJob** [cviebrock/eloquent-sluggable#366]
Hey!
Thanks for a great job guys!

I have found two issues:
1. No unique slug created when `name` is NULL.
2. No unique slug is created when `name` was updated to NULL - it leaves previous slug.

In Ruby on Rails, when you set to unique, you always get an unique slug whatever value of `name` is. If `name` is NULL or becomes NULL on update, slug becomes "-$id". Scenario of name becoming null is very frequent...

**Comment by cviebrock** [comment]
First off, thanks!

1. By design, the package is set to not generate a slug when the source is null.  Changing this would be a big BC issue ... although it could be handled with an additional config option.  Something like `slugOnEmpty` which is false by default.  If it's set to true, it would use the model ID as the unique slug (like RoR does).  I suppose you could also set it to a closure that returned the slug string to use.

2. By default, updating the source of a slug does not regenerate a new slug, unless `onUpdate` is true (which it isn't by default).  However, if it is true and you null out the source field, then rule 1) above applies.  Are you suggesting that instead of leaving the previous slug, when you null the source it should null the slug?

**Comment by cviebrock** [comment]
Actually, the problem with using the model's ID when slugging is that the slug is generated _before_ the model is saved. So the ID hasn't been set yet.

So, the package _could_ save the model first, then generate the slug and update the database.  But that might lead to issues where the act of saving it throws an error (e.g. the `slug` column in the DB is set to `NOT NULL` and/or `UNIQUE`), or triggers a `save` event in another package which might not be the desired behaviour.

If you can think of a good way around this, please let me know!

**Comment by robburley** [comment]
Would a config option like default value be applicable along side your point 1 above have a SlugOnEmpty = true and DefaultSlug = string so you could have blog, blog-1, blog-2, etc?
