### ISSUE TITLE
Nested slugs for relations

### ISSUE THREAD

**Issue by ZapevalovAnton** [cviebrock/eloquent-sluggable#405]
Imagine that there are categories and articles. They are both sluggable. I want to get a SLUG for an article in the form of example.com/**slug_category/slug_article**.

How can I select a record by several slugs?

**Comment by cviebrock** [comment]
There a few ways to do this.  Using SQL/Eloquent and joining the two tables is probably the easiest out-of-the-box way to do it.  Something like this (untested):

```php
$articles = Articles::where('slug', $articleSlug)
    ->whereHas('categories', function($query) use ($categorySlug) {
        $query->where('slug', $categorySlug);
    })
    ->get();
```

But a more elegant solution would be to create a slug on the article class that uses both itself and its category's title.  Again, some sample untested code:

```php
class Category {
    use Sluggable;

    public function sluggable() {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}

class Article {
    use Sluggable;
    public function sluggable() {
        return [
            'slug' => [
                'source' => 'title'
            ],
            'combined_slug' = [
                'source' => ['category.title', 'title']
            ]
        ];
    }
}
```

Then you could simply do `Article::where('combined_slug', $str)`.

**Comment by ZapevalovAnton** [comment]
Thanks for reply. 

I am use first method currently. In the second variant `combined_slug` field is database field? Need migration?After change category title or article title will updated `combined_slug`?

**Comment by cviebrock** [comment]
In the second method, `combined_slug` would need to be a database field so requires a migration.  It's simply a denormalized way of storing the combined slugs on just the one model, to make your SQL queries more efficient.

Changing the title on the article would change the combined slug (since Sluggable operates on the save event for the Article model).  Changing the title on the category, however, would only change `category.slug` and not `article.combined_slug`, so you would need to add some code to handle that ... maybe an event listener, e.g.:

```php
Category::registerModelEvent('slugged', function($category) {
    foreach($category->articles as $article) {
        // update the combined slug somehow, e.g.
        $article->combined_slug = null;
        $article->save();
    }
});
```

**Comment by ZapevalovAnton** [comment]
Thanks.
