### ISSUE TITLE
Slug is unique for two unrelated models

### ISSUE THREAD

**Issue by WalkingInTheDarkness** [cviebrock/eloquent-sluggable#439]
I understand that it is possible (using `scopeWithUniqueSlugConstraints()`) to limit uniqueness check within the same model (so for example we only ensure that the new post that is being created has unique slug for all posts by the same author instead of all posts in the whole table).

Can I achieve opposite effect? Can I extend uniqueness check to more than one table?

Let's say I have two models that use `Sluggable`: `Post` and `Page` and corresponding tables: "`posts`" and "`pages`". For both models I use the same attribute for slug source: "`title`". Models are not related.

Is it possible to ensure that slug that is to be created is unique in both tables? So when I create new `Post` both "`posts.title`" and "`pages.title`" columns are checked? (and vice versa)

Obviously a reason for that is using the same URL for retrieving both models from database, which would be nice, instead of necessity of using some prefix in URL.

Thanks!

**Comment by cviebrock** [comment]
I think you could still do this in the `scopeWithUniqueSlugConstraints()` method.  It might not be the prettiest solution but something joining the two tables might work?  I haven't tried it out, so please post any solutions you come up with.  Otherwise, I'll mark this as a feature request for the next minor version of the package.

(You might also need to override the `scopeFindSimilarSlugs()` method in both models as well to find the next slug value to use in a series -- e.g. `title-1`, `title-2`, etc..)

**Comment by cviebrock** [comment]
Long time without any movement on this, but the solution here probably falls into the category of things that could be done if all the slugs were stored in one polymorphic table, as opposed to a field in each model's table.

Adding the polymorphic-table milestone to this ... but there is no time frame for doing this, presently.

Also, see #379 for a possible solution.
