### ISSUE TITLE
Generate Slugs From Id column

### ISSUE THREAD

**Issue by GerardBalaoro** [cviebrock/eloquent-sluggable#448]
I want to use the [HashIds](https://github.com/vinkla/laravel-hashids) package to generate slugs for my records, however I cannot seem to get it work. My guess is it might be because it relies on the **id** column.

This is my sluggable function, I tried using the hash function first, to test if it would work.

```php
public function sluggable() {
        return [
            'slug' => [
                'source' => 'id',
                'method' => function ($string, $separator) {
                    return hash('sha256', $string);
                }
            ]
        ];
    }
```

Any idea on how to do it? Or its really not possible?

**Comment by cviebrock** [comment]
For new models, the `id` column isn't defined until after the first save, so it doesn't really work as a source for slugs.

If you just want to use HashIds for your model's "slugs", then you probably don't need my package at all ... and you probably don't want to store the hashed ID in the database either.  Just create your models normally, with a regular ID and other data fields.  Then, use something like https://github.com/Propaganistas/Laravel-FakeId to handle the route-model binding.  

Or, if you really want to use HashIds instead of Optimus, you could write your own.  See [here](https://laravel.com/docs/5.7/routing#explicit-binding) and scroll down to where it says **Customizing The Resolution Logic**.
