### ISSUE TITLE
posts/create

### ISSUE THREAD

**Issue by robov** [cviebrock/eloquent-sluggable#453]
When I want to follow conventions I have an /post/create endpoint to create new models.
However, when using you package 'create' is interpreted as the slug, cannot find it, and throws an exception.
any ideas how to handle this nicely ?
or am I missing something ?

Otherwise my ideas are probably to include a reverved slug list... ie.. if slug == create then do not use slug to determine route

**Comment by cviebrock** [comment]
I think this is just a matter of reorganizing your routes so that the `/post/create` comes before the `/post/{slug}` definition (i.e. so the create endpoint matches first).

Worst case: maybe you need to add a condition on the create endpoint, something like this (I'm typing this from memory, so the regex might need tweaking):

```php
Route::get('post/{slug}', function ($slug) {
    //
})->where('slug', '^(?!create$).*');
```
