### ISSUE TITLE
Using ID as part of the slug

### ISSUE THREAD

**Issue by jasonvarga** [cviebrock/eloquent-sluggable#49]
I'm trying to create slugs that start with the ID - so we'd be able to lookup by ID but keep potentially changing slugs in the URLs. eg. `/posts/101-my-post-slug`

In the config file, I have:

```
'build_from' => ['id', 'title'],
```

Only the `title` is used. If I specify different fields, they seem to work too. It's just ID that doesn't want to work.

Is there something I've done incorrectly?
Thanks

**Comment by chicag0** [comment]
Hi @cviebrock 
I'm interested in doing something similar, but I would rather keep the id and slug within the same piece of the url.  In my case I am encoding the model ID to obfuscate the post number.  So 'blog/1' would become 'blog/xRgre-Title-of-blog-post'.

As you said, at the time the model is saved there is not yet an ID, so that part is ignored, but if I resluggify it works great.  This is what I am currently doing:

$blog->save();
$blog->resluggify();
$blog->save();

My question is, can I do something within Slugify or within my Model to do the second save automatically?  I would to just $blog->save() throughout my controllers have something else handle the rest.  Maybe using events or binding?

**Comment by Devbymitch** [comment]
For posterity, here's how I solved this issue. Keep in mind using this will fire off the model saved Event with the slug still null or its previous value. If that doesn't work for your use case you'd just have to add some more logic into the saving method somewhere.
 
**SluggableExtended**
```
trait SluggableExtended
{
    use Sluggable {
    }

    // Overwrite this method
    public static function bootSluggable()
    {
        static::observe(app(SluggableExtendedObserver::class));
    }

    // Added for re-saving after slugged without firing saved event
    public function saveWithoutEvents(array $options=[])
    {
        return static::withoutEvents(function() use ($options) {
            return $this->save($options);
        });
    }
}
```
**SluggableExtendedObserver**
``` 
class SluggableExtendedObserver extends SluggableObserver
{
    public function saving(Model $model)
    {
        //return $this->generateSlug($model, 'saving');
    }

    public function saved(Model $model)
    {
        $generateReturn = $this->generateSlug($model, 'saved');
        $model->saveWithoutEvents();
        return $generateReturn;
    }
}
```
