### ISSUE TITLE
Slugs that include ' / ' get replaced by ' - '

### ISSUE THREAD

**Issue by kpapag** [cviebrock/eloquent-sluggable#513]
- [ ] steps taken to reproduce your issue

When updating a model but not changing the slug field, '/' gets replaced by '-'

- [ ] your configuration file(s), where relevant

In config/sluggable.php, 'onUpdate' => true,

- [ ] a copy of your Models that use or extend this package (just the relevant parts!)

Every model that 

use Sluggable;
use SluggableScopeHelpers;

- [ ] any other code we might need to help

If 'onUpdate' => false (in configuration), problem does not occur. 

If this is intended, and not a bug, where in the package can i change this behavior? I really need this simple feature.

Thank you in advance.

**Comment by kpapag** [comment]
i should note that nothing else changes in the slug string, just the '/' char keeps getting replaced by '-'

**Comment by oleaass** [comment]
I believe this is preferred behavior considering / are treated as path separator in urls. Using slugs with / in them would cause nothing but trouble..

**Comment by cviebrock** [comment]
Sorry for the delay.

If you are generating slugs with `/` because you want to use them for pathing, I would suggest you reconsider how you are using them.  For example, generating a slug for a book where you want `authors-name/book-title` as the slug ... in my opinion that should really be two slugs (one for the author, one for the book), and the logic to figure it out can live in your controller.

That said, the [default slug engine](https://github.com/cocur/slugify) is doing this for you.  You can adjust its behaviour with the [customizeSlugEngine](https://github.com/cviebrock/eloquent-sluggable#customizeslugengine) method.
