### ISSUE TITLE
Always add unique suffix?

### ISSUE THREAD

**Issue by vntrungld** [cviebrock/eloquent-sluggable#517]
Do we have something like this feature?
Eg: I have 3 posts:
post
post-1
post-2

It is possible for us to change it to:
post-1
post-2
post-3

**Comment by aske-cph** [comment]
Did you find a solution since you closed the issue? 

I may be looking for something similar: https://github.com/cviebrock/eloquent-sluggable/issues/539

**Comment by cviebrock** [comment]
@aske-cph If you can use the latest version of the package, you can change it so the models are slugged after they are saved.  In this case, the models' IDs can be part of the slug source.  That would be a unique "suffix" for each slug.  Something like:

```php
class Posts {

    use Sluggable;

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => ['title', 'id']
            ]
        ];
    }

    public function sluggableEvent(): string
    {
        return SluggableObserver::SAVED;
    }

}
```

If you set `onUpdate` to `true`, then you could use this for routing as well, since the title will always be unique even if the title is changed (e.g. `my-first-post-1` and then `ive-changed-the-title-1`, etc.).
