### ISSUE TITLE
Scoping new model?

### ISSUE THREAD

**Issue by Keiron** [cviebrock/eloquent-sluggable#574]
```
 public function author(): BelongsTo
    {
        return $this->belongsTo(Author::class);
    }


public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug): Builder
    {
        $author = $model->author; // Author is null!

        return $query->where('author_id', $author->getKey());
    }
```

I'm using scopeWithUniqueSlugConstraints to scope a model by an ID in the model, which I can see how will work when editing a model because the author will exist, but when creating a new model I'm finding $author is null so I can't scope it?

Any advice appreciated?

**Comment by cviebrock** [comment]
How are you creating the model?  I would think if you create the `Author` first, this wouldn't be an issue ...?

**Comment by Keiron** [comment]
Sorry, I should have said and yes I totally agree with you when you're saving the model.

I'm using livewire to post to a route and generate the slug to show during the creation, before saving! I saw a couple of tutorials doing this and was trying to adapt it for my needs but I need scoping.

I'm passing the author in the route to the slug creation, but don't seem to be able to make sluggable then use that?

**Comment by cviebrock** [comment]
Can you post the code of your controller or whatever that actually creates the models?  I assume you're POSTing the ID of the `Author` model along with all the new attributes of the `Post` model (or whatever it is).  In this case, you might need to actually load the Author first, associate it with the Post, and then save.

```php
$author = Author::find($author_id);

$post = new Post($array_of_attributes);
$post->author()->associate($author);
$post->save();
```
\* untested code

**Comment by Keiron** [comment]
I'm trying to do generate a slug pre-creating the model (and give the user the option to override), similar to this article  but via Livewire: [Generate Slug Keyword from Title: Laravel + AJAX](https://laraveldaily.com/generate-slug-keyword-from-title-laravel-ajax/)


So at the point the slug is checked via an ajax or livewire call the author ID doesn't yet exist on the model, we have it but as we know which author the book is being created for, but I can't see a way to pass this to SlugService::createSlug ?

```
public function check_slug(Request $request)
{
    // Old version: without uniqueness
    $slug = str_slug($request->title);

    // New version: to generate unique slugs
    $slug = SlugService::createSlug(Page::class, 'slug', $request->title);

    return response()->json(['slug' => $slug]);
}
```
Any help appreciated?

**Comment by cviebrock** [comment]
I think instead of this:

```php
$slug = SlugService::createSlug(Page::class, 'slug', $request->title);
```

you will have to create an actual `Page` model, attach an `Author` model, and then pass the Page as the first argument.  I realize you haven't actually persisted those models yet, so that might not even work.  But for the slug service to know how to read attributes from related models, or scope the unique constraint, those would have to be there already.

Thinking a bit more ... I'm assuming you want the slugs to be unique per author.  So Bob Smith's page "My First Post" could have the same slug as Mary Black's page "My First Post" .. right?  In that case, the only chance of it be non-unique would be for new pages by the same author ... in which case I assume your author _does_ exist and you could attach that to the "fake" Page model you are passing to the service.  If it's a new page _and_ a new author, then the author part is irrelevant, since there can't be a page with the same slug for that author already.

I'm not actually sure there is an easy way to solve this automatically.  You could try:

```php
public function scopeWithUniqueSlugConstraints(Builder $query, Model $model, $attribute, $config, $slug): Builder
{
    $author = $model->author;

    if ($author === null) {
        return $query;
    }
    return $query->where('author_id', $author->getKey());
}
```

**Comment by cviebrock** [comment]
Closing due to no response.  Feel free to re-open or comment if you are still having issues.
