### ISSUE TITLE
Ignore id when on_update is true

### ISSUE THREAD

**Issue by rodurma** [cviebrock/eloquent-sluggable#59]
For example, I have this sequence when on_update is true:

I created "My Blog Post" (id:1) that created "my-blog-post" slug.
I create another "My Blog Post" (id:2) that created "my-blog-post-1" slug.
I updated "My Blog Post" (id:2) that created "my-blog-post-2" slug.
I updated "My Blog Post" (id:2) that created "my-blog-post-3" slug.
I updated "My Blog Post" (id:2) that created "my-blog-post-4" slug.
I updated "My Blog Post" (id:2) that created "my-blog-post-5" slug.
...

**Comment by alireza-h** [comment]
This is the same problem I get.

**Comment by unitedworx** [comment]
Why do you do this? You are not supposed to call this manually on every update! 
 $recipe->resluggify();

This might be your problem since you are forcing slugify to update the slug on each update based on the title. If you want such behaviour you need to tell slugify to do this by setting on_update setting to true.

**Comment by alireza-h** [comment]
Excuse me for my bad English!
I have problem with on_update setting. I don't use resluggify() method manually.

**Comment by unitedworx** [comment]
do you have use_cache set to true? if yes try setting that to false and see if this solves your problem.

**Comment by alireza-h** [comment]
use_cache has default false value.
