### ISSUE TITLE
Case-sensitivity and slug uniqueness

### ISSUE THREAD

**Issue by o15a3d4l11s2** [cviebrock/eloquent-sluggable#606]
At the moment we have already-existing slugs that are not explicitly lowercase, for example `Page-Slug`. If I try to replicate and store the model, I get an error that my slug is no longer unique. The reason is that when `replicate` generates the slug, it checks if the same slug already exists and even when `unique` is set to `true`, the check https://github.com/cviebrock/eloquent-sluggable/blob/16e21db24d80180f870c3c7c4faf3d3af23f4117/src/Services/SlugService.php#L286 determines that `page-slug` is not the same as `Page-Slug`, so the result is a new (replicated) model with the same slug.

I am using v.8.0.8 of the package, but if I see it correctly the mentioned logic is still the same.

Since the collection is case-sensitive and the database sensitivity depends on the OS and/or settings, is there any possible solution for this issue other than updating all existing records to lowercase them?

**Comment by cviebrock** [comment]
I think if you are using this package on a system were the database sensitivity is important, then you should take that into account when defining the method used to generate slugs.

By default, the package uses the `cocur/slugify` method, which should convert everything to lowercase.  I see you are coming into this with a bunch of pre-existing slugs that aren't explicitly lowercase, so I think the easiest option is to redefine the `slugEngineOptions` in the configuration so that slugs aren't lowercased by default, e.g.:

```php
public function sluggable(): array
{
    return [
        'slug' => [
            'source' => 'title',
            'slugEngineOptions' => [
                'lowercase' => false
            ]
        ]
    ];
}
```

Otherwise, I think you would need to either convert all your existing slugs to lowercase (if that's how new slugs will be generated), or create a custom `method` in the configuration that returns slugged strings in a mixed-case format.

Make sense?

**Comment by o15a3d4l11s2** [comment]
Happy New Year, stay healthy and happy. Thank you for your input. The easiest solution for me was to lowercase all slugs (they are used for url generation, so absolutely makes sense) and I left the configuration unchanged.
