### ISSUE TITLE
Not working properly with Unicode characters ?

### ISSUE THREAD

**Issue by vdharshan** [cviebrock/eloquent-sluggable#98]
Love this package, using on every projects. however I tried with a unicode language and it produce slugs like "-5" etc (it takes blank title)

**Comment by cviebrock** [comment]
What do you have set for `method` in your configuration?  By default, slugs are just created using `Str::slug`, which probably doesn't work on unicode strings.

I'm planning on switching to a 3rd party package to handle the actual slugging ... but you can do it already:

- Include another package in your project's `composer.json` file, such as [cocur/slugify](/cocur/slugify)
- add the provider and alias entries in `app/config/app.php`
```php
'providers' => array(
    "Cocur\Slugify\Bridge\Laravel\SlugifyServiceProvider",
);

'aliases' => array(
    "Slugify" => "Cocur\Slugify\Bridge\Laravel\SlugifyFacade",
);
```
- update your `method` in sluggable config to:
```php
    'method' => array('Slugify','slugify')
```

Those instructions might need some tweaking, but I believe that should work for you.  As long as `cocur/slugify` knows how to handle those particular unicode characters, it should be fine.  Otherwise, just create your own function or method that takes your unicode string as input and returns the slugged version, and use that as the `method`.

**Comment by vtxmg** [comment]
thanks :)

**Comment by hgokturk** [comment]
How exactly to use Slugify in cooperation with Eloquent Sluggable? For example in my controller:
$slugify = new Slugify();
$slugify->addRule('ö', 'o');
and Eloquent Sluggable is also set. But when i:
$event = new Blog;
$event->title = "Ödeme ücretler";
$event->save();

in db, title is correctly set but slug is "oe" for "Ö" which actually is supposed to be "o" according to $slugify->addRule. What i'm missing here?

**Comment by cviebrock** [comment]
Personally, I would put all those rules in the `getSlugEngine()` method itself, as I do for [one of the tests](https://github.com/cviebrock/eloquent-sluggable/blob/master/tests/models/PostCustomEngine.php).

Depending on which language you are slugging, you also might want to look at the [rulesets](https://github.com/cocur/slugify#rulesets) features of Slugify.  On first glance, you may just be able to replace all your custom rules with a call to `$slugify->activateRuleset(...)`, or change the priority order of rule sets when instantiating Slugify.
